# Generated by Django 2.1.1 on 2018-09-08 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('task', models.TextField(max_length=300, verbose_name='やること')),
                ('dead_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='期限')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
