# Generated by Django 2.1.1 on 2018-09-07 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='Protected', to=settings.AUTH_USER_MODEL),
        ),
    ]
